project:
  type: officequarto

format:
  docx:
    reference-doc: original.docx
    officequarto-keep-rendered: true
    officequarto-styles:
      body: "Fließtext ACME"
      ul_style: "Aufzählung ACME"      # officedown-Alias fuer list-bullet, siehe README
      list-number: "Nummerierung ACME"
      list-letter: "Buchstabierung ACME"
    officequarto-pandoc-styles:
      code-block: "Code ACME"
    officequarto-tables:
      style: "Tabelle ACME"
      layout: fixed
      tables_width: 0.8         # officedown-Alias fuer width, siehe README
