project:
  type: officequarto

format:
  docx:
    reference-doc: original.docx
    officequarto-styles:
      body: "Fließtext ACME"
      list-bullet: "Aufzählung ACME"
      list-number: "Nummerierung ACME"
