d <- dirname(sub("--file=", "", grep("--file=", commandArgs(), value = TRUE)))
source(file.path(d, "..", "experiments", "lib.R"))
r <- render_docx(d, "demo.qmd")
report("render ok", r$status == 0)
report("TOC field (marker)", has(r$xml, "TOC \\o"))
report("page break (marker)", has(r$xml, "w:type=\"page\""))
report("landscape sectPr (marker)", has(r$xml, "w:orient=\"landscape\""))
report("portrait-ending sectPr before it", length(gregexpr("<w:sectPr", r$xml, fixed = TRUE)[[1]]) >= 3)
report("chained plot hook ran (PLOT-HOOK-NOTE)", has(r$xml, "PLOT-HOOK-NOTE: chained"))
report("Quarto figure caption + 'Figure 1' kept", has(r$xml, "WIDE-FIGURE") && (has(r$xml, "Figure&#160;1") || has(r$xml, "Figure 1") || has(r$xml, "Figure 1")))
report("crossref hyperlink fig-wide kept", has(r$xml, "w:anchor=\"fig-wide\""))
report("no marker comments left", !has(r$xml, "BLOCK_"))
if (r$status != 0) cat(tail(r$log, 12), sep = "\n")
