## Core logic for Gruppe 3 (table captions) of the officedown option port:
## officequarto.tables.caption.style/prefix/separator/number-bold.
## oq_apply_captions() (the actual formatting logic) is generic and is
## reused by Gruppe 5 (figure captions, plot-caption-mapping.R) - only
## oq_find_table_caption_paragraphs() is table-specific. Part of the
## officequarto R package - used by oq_writeback() (R/writeback.R), not run
## standalone. Requires: xml2, oq_set_pstyle() from style-mapping.R (in the
## same package namespace, no explicit load order needed).
##
## `tnd`/`tns` (officedown: per-section numbering depth, e.g. "2-1") were
## deliberately NOT ported - Quarto/Pandoc numbers tables exclusively
## globally/sequentially, there's no section-level numbering to tap into;
## a from-scratch implementation would be a substantially bigger,
## standalone feature (tracking heading boundaries, maintaining its own
## numbering) - see README.
##
## Background/core problem (see dev/spike-notes.md for the full empirical
## derivation): Quarto's table captions in the docx output are currently
## static, already-baked-in text (no real Word SEQ field) - "Table 1: My
## Title" is ONE <w:r><w:t> run. pre/sep/number-bold can therefore only be
## implemented via text parsing. The prefix text generated by Pandoc
## depends on the user's crossref.tbl-title/title-delim settings AND is
## additionally altered by Pandoc's own smart-typography conversion (e.g.
## "--" -> en dash "–", non-breaking space before the number), which is why
## the generated text CANNOT reliably be predicted/reconstructed from the
## configuration. Instead, the anchor is the number itself: digits are
## unaffected by the typography conversion, and officequarto counts table
## captions itself in document order - identical to Pandoc's own count,
## since only tables WITH a caption produce a caption paragraph at all.
##
## officequarto.crossref.auto-number (no officedown equivalent) solves the
## core problem above fundamentally instead of working around it: instead
## of parsing the already-baked-in text, the number is replaced by a real,
## live-numbering Word SEQ field (see oq_convert_caption_to_field() below,
## analogous to {officedown}'s/{officer}'s own field generation,
## bytecode-introspected - see dev/spike-notes.md Spike P). A caption is
## thereby either fully static text (previous behavior) or fully
## field-based - see oq_apply_captions().

## Finds all table caption paragraphs in document order.
##
## Pandoc does NOT always use the same style for table captions: for a
## Quarto crossref-managed table (`{#tbl-xyz}`) it uses "ImageCaption" (the
## same style as for figures, see oq_find_plot_caption_paragraphs()) and
## wraps caption+table in a synthetic 1x1 wrapper table; for a plain Pandoc
## caption without a crossref ID (`: My caption`, no `{#tbl-...}`) it
## instead uses "TableCaption" and creates NO wrapper table at all - the
## caption paragraph and `w:tbl` then sit as plain siblings directly in the
## document body (empirically verified against ../hello-wordto, see
## dev/spike-notes.md).
##
## The style alone is therefore not enough to detect this (especially
## since "ImageCaption" is ambiguous), AND the original heuristic "parent
## element has some w:tbl child" is unusable in the non-wrapper case: in
## the document body (w:body), the caption AND (possibly completely
## unrelated) tables sit as direct siblings next to each other, so this
## check also falsely fires on a figure caption as soon as any table
## exists anywhere in the document at all (a real bug that swapped table
## and figure captions in ../hello-wordto). Instead, positional adjacency
## is checked directly: the caption paragraph must be IMMEDIATELY (not just
## somewhere in the same parent element) followed by a w:tbl - this holds
## equally for the wrapper and the non-wrapper case (Pandoc's default
## position in both cases is "caption before the table").
#' @noRd
oq_find_table_caption_paragraphs <- function(document_doc, ns) {
  xml2::xml_find_all(
    document_doc,
    "//w:p[w:pPr/w:pStyle/@w:val='TableCaption' or w:pPr/w:pStyle/@w:val='ImageCaption'][following-sibling::*[1][self::w:tbl]]",
    ns
  )
}

## Finds the content node belonging to a table caption (the immediately
## following w:tbl - nested in the same wrapper cell in the crossref case,
## or a plain sibling element in the non-wrapper case, see
## oq_find_table_caption_paragraphs()) - for oq_apply_captions()'s $above
## handling (see there). NA if no directly following table exists (e.g.
## for an atypical document).
#' @noRd
oq_table_caption_content <- function(caption_p, ns) {
  xml2::xml_find_first(caption_p, "./following-sibling::*[1][self::w:tbl]", ns)
}

## Splits the text of a caption run into [text before the number] [number]
## [text after the number up to the actual caption text] [rest]. The
## expected number is passed in from outside (officequarto counts it
## itself, see above) and is anchored via a word-boundary lookaround (not
## via a plain substring match, otherwise e.g. "1" would falsely match
## inside "1990"). matched=FALSE if the expected number wasn't found in the
## expected format (e.g. because the caption doesn't match Pandoc's
## generated format) - the caller then leaves the text unchanged instead
## of guessing something wrong.
#' @noRd
oq_split_caption_text <- function(text, expected_number) {
  pattern <- paste0(
    "^(.*?)(?<![\\p{L}\\p{N}])(", expected_number, ")(?![\\p{L}\\p{N}])([^\\p{L}\\p{N}]*)"
  )
  groups <- regmatches(text, regexec(pattern, text, perl = TRUE))[[1]]
  if (length(groups) == 0) {
    return(list(matched = FALSE))
  }
  list(
    matched = TRUE,
    title_prefix = groups[2],
    number = groups[3],
    generated_sep = groups[4],
    rest = substr(text, nchar(groups[1]) + 1, nchar(text))
  )
}

## Writes the (possibly newly assembled) caption text back into the first
## run of a caption. number_bold: NULL (not configured - leave formatting
## unchanged, a single run remains) or TRUE/FALSE (explicit bold switch for
## the prefix+number portion - for this the run is split into two runs:
## the first carries prefix+number plus explicit w:b, the second carries
## separator+caption text WITHOUT explicit w:b, so it inherits the style's
## formatting instead of overriding it). Any further, already-existing runs
## after that (e.g. inline formatting in a human-authored caption text) are
## left untouched - they correctly follow the new second run structurally.
#' @noRd
oq_write_caption_run <- function(first_run, t_node, ns, pre, number, sep, rest, number_bold) {
  if (is.null(number_bold)) {
    xml2::xml_text(t_node) <- paste0(pre, number, sep, rest)
    return(invisible(NULL))
  }

  xml2::xml_text(t_node) <- paste0(pre, number)
  rpr <- xml2::xml_find_first(first_run, "./w:rPr", ns)
  if (is.na(rpr)) {
    rpr <- xml2::xml_add_child(first_run, "w:rPr", .where = 0)
  }
  b_node <- xml2::xml_find_first(rpr, "./w:b", ns)
  if (is.na(b_node)) {
    b_node <- xml2::xml_add_child(rpr, "w:b")
  }
  xml2::xml_attr(b_node, "w:val") <- if (isTRUE(number_bold)) "1" else "0"

  second_run <- xml2::xml_add_sibling(first_run, "w:r", .where = "after")
  second_t <- xml2::xml_add_child(second_run, "w:t")
  xml2::xml_attr(second_t, "xml:space") <- "preserve"
  xml2::xml_text(second_t) <- paste0(sep, rest)

  invisible(NULL)
}

## Moves a caption to the position before (above=TRUE) or after
## (above=FALSE) its associated content node (nested w:tbl for tables,
## image paragraph for figures - see the content_finder parameter of
## oq_apply_captions()), within the same Pandoc wrapper cell. Via
## copy+remove instead of a direct "move" - xml2 offers no native way to
## move a node between positions, and `xml_add_sibling(..., copy = FALSE)`
## still produces a copy and does NOT remove the original (empirically
## verified) - the copy step therefore has to be explicitly supplemented
## with an xml_remove() of the original. Works regardless of the previous
## position (no upfront check needed, since it's idempotent: a caption
## already correctly positioned ends up unchanged in the same place after
## copy+remove).
#' @noRd
oq_move_caption <- function(caption_p, content_node, above) {
  where <- if (isTRUE(above)) "before" else "after"
  xml2::xml_add_sibling(content_node, caption_p, .where = where, copy = TRUE)
  xml2::xml_remove(caption_p)
  invisible(NULL)
}

## Finds the name of the bookmark (w:bookmarkStart/@name) that marks a
## caption as a crossref target - a sibling of the caption within the same
## Pandoc wrapper CELL (see oq_table_caption_content()/
## oq_plot_caption_content()). NA if none is found - in particular for a
## plain (non-crossref) caption, whose parent element is NEVER a wrapper
## cell (see below). For Gruppe 9 (officequarto.crossref.numbered, see
## crossref-mapping.R) - there, this name is used as a key to trace an
## @tbl-xyz/@fig-xyz cross-reference back to this caption.
##
## IMPORTANT, found via a real render against ../hello-wordto (no synthetic
## test would have caught this, see below at oq_find_caption_bookmark()):
## the parent element of a caption without a crossref ID is NEVER a
## wrapper cell, but typically w:body itself (no wrapper table in the
## non-crossref case, see oq_find_table_caption_paragraphs()) - there, ALL
## of the document's possible bookmarks sit as siblings (e.g. every
## heading anchor bookmark). A direct "first w:bookmarkStart in the parent
## element" match would be arbitrary in this case (in practice it hit the
## nearest heading bookmark, completely unrelated to the caption).
## Therefore: only search if the parent element is actually a wrapper cell
## (w:tc) - that's structurally exactly the condition for "this caption has
## an associated Pandoc bookmark at all". Note an xml2 quirk: w:name is
## addressed unprefixed as "name" when READING (unlike when WRITING, where
## "w:val" etc. must be prefixed - see CLAUDE.md) - empirically verified.
#' @noRd
oq_caption_anchor_name <- function(caption_p, ns) {
  parent <- xml2::xml_parent(caption_p)
  if (!identical(xml2::xml_name(parent), "tc")) return(NA_character_)
  bookmark <- xml2::xml_find_first(parent, "./w:bookmarkStart", ns)
  if (is.na(bookmark)) return(NA_character_)
  xml2::xml_attr(bookmark, "name")
}

## Like oq_caption_anchor_name(), but additionally returns the nodes
## themselves plus the bookmark ID - for oq_convert_caption_to_field()
## (officequarto.crossref.auto-number), which removes the existing bookmark
## pair and replaces it with a new one (see there). IMPORTANT (empirically
## verified, see dev/spike-notes.md Spike P, also cross-checked against
## ../hello-wordto): w:bookmarkStart/w:bookmarkEnd are pure position
## markers, not a tightly adjacent empty pair between caption and
## table/figure - Pandoc's bookmark typically spans the ENTIRE wrapper-cell
## content (caption+table, or image+caption). w:bookmarkEnd is therefore
## located via its matching @id, not by adjacency.
##
## A REAL bug found in ../hello-wordto (via a real render, not uncovered by
## synthetic tests - see dev/spike-notes.md): a plain (non-crossref)
## caption has NO Pandoc bookmark of its own, but its parent element
## (typically w:body) nonetheless contains many completely unrelated
## bookmarks (e.g. every heading anchor in the document). Without the
## `xml_name(parent) == "tc"` guard, the function incorrectly grabbed the
## nearest, completely unrelated heading bookmark from w:body, then REMOVED
## it as the supposed "old caption bookmark" and created a new SEQ field
## under its name - thereby destroying real, independent jump targets
## (heading anchors) in the document. The guard ensures that ONLY real
## wrapper cells (the only structure in which Pandoc actually creates a
## caption bookmark at all) are ever considered as a candidate. Returns
## NULL if the parent element is not a wrapper cell or no bookmark is
## found.
#' @noRd
oq_find_caption_bookmark <- function(caption_p, ns) {
  parent <- xml2::xml_parent(caption_p)
  if (!identical(xml2::xml_name(parent), "tc")) return(NULL)
  start <- xml2::xml_find_first(parent, "./w:bookmarkStart", ns)
  if (is.na(start)) return(NULL)
  id <- xml2::xml_attr(start, "id")
  end <- xml2::xml_find_first(parent, sprintf("./w:bookmarkEnd[@w:id='%s']", id), ns)
  if (is.na(end)) return(NULL)
  list(start = start, end = end, id = id, name = xml2::xml_attr(start, "name"))
}

## Clones (if present) orig_rpr as the first child of `run` and optionally
## sets w:b explicitly (number_bold: NULL = unchanged/not created,
## TRUE/FALSE = explicit bold switch) - a shared helper for the rPr
## transfer when building new field runs, so the clone+bold logic doesn't
## have to be maintained twice: used by oq_convert_caption_to_field() here
## (SEQ field, number_bold possible) AND by oq_apply_crossref_fields() in
## crossref-mapping.R (REF field, always with number_bold = NULL, i.e.
## plain rPr cloning without a bold override). Creates no w:rPr child if
## neither orig_rpr exists nor number_bold is set.
#' @noRd
oq_clone_rpr_with_bold <- function(run, orig_rpr, ns, number_bold = NULL) {
  if (!is.na(orig_rpr)) {
    rpr <- xml2::xml_add_child(run, orig_rpr, .where = 0)
  } else if (!is.null(number_bold)) {
    rpr <- xml2::xml_add_child(run, "w:rPr", .where = 0)
  } else {
    return(invisible(NULL))
  }
  if (!is.null(number_bold)) {
    b_node <- xml2::xml_find_first(rpr, "./w:b", ns)
    if (is.na(b_node)) b_node <- xml2::xml_add_child(rpr, "w:b")
    xml2::xml_attr(b_node, "w:val") <- if (isTRUE(number_bold)) "1" else "0"
  }
  invisible(NULL)
}

## Converts a caption from static text into a real, live-numbering Word
## SEQ field (officequarto.crossref.auto-number) - analogous to
## {officedown}'s/{officer}'s own field generation (bytecode-introspected,
## not guessed): every field consists of exactly 3 runs (fldChar begin ->
## instrText -> fldChar end, both fldChars with w:dirty="true"), WITHOUT
## fldChar type="separate" and WITHOUT a cached result run - Word computes
## these "dirty" simple fields automatically on layout/open, with no
## w:updateFields in settings.xml at all (deliberately NOT set there,
## exactly like {officedown} - see README/CLAUDE.md).
##
## Replaces the first run with: [prefix text run] [new bookmarkStart]
## [3-run SEQ field: "SEQ <seq_id> \* Arabic"] [new bookmarkEnd]
## [separator+rest text run]. seq_id is "Table"/"Figure" (fixed, not
## configurable - as with {officedown}'s own convention; the visible
## prefix text remains independently configurable via $prefix). The
## bookmark is taken over from the existing (widely spanning) Pandoc
## bookmark (same name, same ID - see oq_find_caption_bookmark()), but
## newly and tightly wrapped around just the digit (matching {officer}'s
## run_autonum(bkm_all = FALSE) default behavior), so existing crossref
## hyperlinks with @w:anchor pointing to the same name keep working
## unchanged.
##
## The rPr of the original first run (if present) is cloned onto the
## prefix run and all three field runs (preserves the formatting of the
## "prefix+number" portion, which is now spread across several runs
## instead of previously being a single run), with w:b optionally forced
## when number_bold is set (analogous to the existing 2-run bold split in
## oq_write_caption_run()). The final separator+rest run deliberately gets
## NO rPr (inherits the formatting of the - possibly remapped - caption
## style), exactly like the second run in oq_write_caption_run().
##
## Returns NA_character_ (no field created, paragraph left untouched - the
## caller falls back to oq_write_caption_run() in this case, see
## oq_apply_captions()) if no bookmark is found - the same "don't guess"
## philosophy as the matched=FALSE case. Only called when
## caption_options$auto_number is TRUE AND split$matched is TRUE (see
## oq_apply_captions()).
#' @noRd
oq_convert_caption_to_field <- function(caption_p, ns, first_run, split, seq_id, caption_options) {
  bookmark <- oq_find_caption_bookmark(caption_p, ns)
  if (is.null(bookmark)) return(NA_character_)

  pre <- if (!is.null(caption_options$prefix)) caption_options$prefix else split$title_prefix
  sep <- if (!is.null(caption_options$separator)) caption_options$separator else split$generated_sep
  number_bold <- caption_options$number_bold
  orig_rpr <- xml2::xml_find_first(first_run, "./w:rPr", ns)
  apply_pr <- function(run) oq_clone_rpr_with_bold(run, orig_rpr, ns, number_bold)

  anchor <- first_run
  add_after <- function(tag) {
    anchor <<- xml2::xml_add_sibling(anchor, tag, .where = "after")
    anchor
  }

  prefix_run <- add_after("w:r")
  prefix_t <- xml2::xml_add_child(prefix_run, "w:t")
  xml2::xml_attr(prefix_t, "xml:space") <- "preserve"
  xml2::xml_text(prefix_t) <- pre
  apply_pr(prefix_run)

  bookmark_start <- add_after("w:bookmarkStart")
  xml2::xml_attr(bookmark_start, "w:id") <- bookmark$id
  xml2::xml_attr(bookmark_start, "w:name") <- bookmark$name

  begin_run <- add_after("w:r")
  apply_pr(begin_run)
  begin_fld <- xml2::xml_add_child(begin_run, "w:fldChar")
  xml2::xml_attr(begin_fld, "w:fldCharType") <- "begin"
  xml2::xml_attr(begin_fld, "w:dirty") <- "true"

  instr_run <- add_after("w:r")
  apply_pr(instr_run)
  instr_node <- xml2::xml_add_child(instr_run, "w:instrText")
  xml2::xml_attr(instr_node, "xml:space") <- "preserve"
  xml2::xml_text(instr_node) <- sprintf("SEQ %s \\* Arabic", seq_id)

  end_run <- add_after("w:r")
  apply_pr(end_run)
  end_fld <- xml2::xml_add_child(end_run, "w:fldChar")
  xml2::xml_attr(end_fld, "w:fldCharType") <- "end"
  xml2::xml_attr(end_fld, "w:dirty") <- "true"

  bookmark_end <- add_after("w:bookmarkEnd")
  xml2::xml_attr(bookmark_end, "w:id") <- bookmark$id

  rest_run <- add_after("w:r")
  rest_t <- xml2::xml_add_child(rest_run, "w:t")
  xml2::xml_attr(rest_t, "xml:space") <- "preserve"
  xml2::xml_text(rest_t) <- paste0(sep, split$rest)

  xml2::xml_remove(first_run)
  xml2::xml_remove(bookmark$start)
  xml2::xml_remove(bookmark$end)

  bookmark$name
}

## Applies caption_options ($style/$prefix/$separator/$number_bold/$above,
## each optional) to an already-found set of caption paragraphs (in place,
## via xml2's reference semantics). Generic for both table AND figure
## captions - the formatting logic itself is identical for both, only the
## search for the paragraphs (and, for $above, the search for the
## associated content node via content_finder) differs
## (oq_find_table_caption_paragraphs()/oq_table_caption_content() here vs.
## oq_find_plot_caption_paragraphs()/oq_plot_caption_content() in
## plot-caption-mapping.R for Gruppe 5). content_finder: function(caption_p,
## ns) -> content node or NA; only needed when caption_options$above is
## set. Numbers captions itself in document order (1-based), identical to
## Pandoc's own count - since table and figure captions have separate
## numbering sequences in Pandoc ("Table 1"/"Figure 1" independent of each
## other), this function must be called SEPARATELY for tables and figures,
## each with its own, already-found set.
##
## IMPORTANT (a real bug found via a real render against ../hello-wordto -
## no synthetic test would have caught it, since it requires a specific
## mix of plain and crossref-numbered captions of the SAME type in the
## SAME document order): the counter for the expected number value (passed
## to oq_split_caption_text()) may ONLY be incremented for captions
## actually numbered by Quarto (= marked via a bookmark, see
## oq_caption_anchor_name()) - NOT for every found caption regardless of
## its type. Quarto doesn't number plain (non-crossref) captions at all (no
## counter step of its own), so it only counts real crossref-numbered
## tables/figures. If officequarto instead counted EVERY found caption (the
## original, buggy implementation), the counter would drift by one at
## every plain caption appearing BEFORE a crossref-numbered caption of the
## same type - the expected number then no longer matches the number
## actually baked in, oq_split_caption_text() incorrectly fails to match,
## and the crossref-numbered caption is silently left untouched (for every
## feature: prefix/separator/number-bold, crossref.numbered: false AND
## crossref.auto-number). `oq_caption_anchor_name()` is therefore the gate
## HERE: plain captions (NA) are skipped entirely (neither counted nor
## parsed) - only real, bookmark-marked captions participate in
## counting/parsing at all.
##
## $above is deliberately applied as the LAST step per caption (after
## style remap and text rewrite) - only after all changes have been made
## to the still-attached node is it moved via copy+remove; moving it
## BEFORE the other steps would mean continuing to work on a node already
## detached from the document tree. Applies unchanged for EVERY found
## caption (plain ones too) - $above is a pure positioning concern,
## independent of numbering.
##
## The actual caption text (oq_split_caption_text()'s $rest) is ALWAYS
## determined, regardless of whether prefix/separator/number_bold are
## configured at all (not only when needs_text_rewrite) - Gruppe 9
## (officequarto.crossref.numbered: false) needs this text even when
## Gruppe 3/5 themselves aren't configured at all, just running "silently"
## alongside to enable the crossref rewrite. Only the actual WRITING into
## the paragraph (oq_write_caption_run()) stays tied to
## needs_text_rewrite.
##
## Returns list(n_found, n_text_rewritten, n_field_converted, n_moved,
## anchor_text, converted_anchors) - n_text_rewritten can be smaller than
## n_found if a caption wasn't in the expected "prefix number separator
## text" format (oq_split_caption_text() couldn't anchor the number) and
## was therefore left untouched; n_moved can be smaller than n_found if no
## associated content node was found for a caption. anchor_text is a named
## character vector bookmark name -> caption text (without
## prefix/number/separator), for captions where both a bookmark and
## successfully parsed text were found. n_field_converted/converted_anchors:
## see caption_options$auto_number below - converted_anchors is a character
## vector of the bookmark names of all captions successfully converted
## into a SEQ field (empty if auto_number isn't set), for the "auto-number"
## group's cross-reference conversion (see
## crossref-mapping.R/oq_apply_crossref_fields()).
##
## caption_options$auto_number (officequarto.crossref.auto-number): if
## TRUE, oq_convert_caption_to_field() is called per caption INSTEAD OF
## (never in addition to) oq_write_caption_run() - a caption is either
## fully static text or fully field-based, never a hybrid. In this case
## `seq_id` ("Table"/"Figure") must be passed in. If
## oq_convert_caption_to_field() returns NA_character_ (no matching
## bookmark found, see there), the caption falls back to
## oq_write_caption_run(), provided prefix/separator/number_bold are
## configured (needs_text_rewrite) - a failed field conversion shouldn't
## mean the caption is left completely untouched.
#' @noRd
oq_apply_captions <- function(document_doc, captions, caption_options, content_finder = NULL, seq_id = NULL) {
  ns <- xml2::xml_ns(document_doc)

  n_found <- length(captions)
  n_text_rewritten <- 0L
  n_field_converted <- 0L
  n_moved <- 0L
  anchor_text <- character(0)
  converted_anchors <- character(0)

  needs_text_rewrite <- !is.null(caption_options$prefix) ||
    !is.null(caption_options$separator) ||
    !is.null(caption_options$number_bold)

  numbered_count <- 0L
  for (p in captions) {

    if (!is.null(caption_options$style)) {
      oq_set_pstyle(p, ns, caption_options$style)
    }

    ## anchor_name (NA for a plain caption not marked via a bookmark - see
    ## oq_caption_anchor_name()) decides whether this caption participates
    ## in counting/parsing at all (see above).
    anchor_name <- oq_caption_anchor_name(p, ns)
    if (!is.na(anchor_name)) {
      numbered_count <- numbered_count + 1L
      runs <- xml2::xml_find_all(p, "./w:r", ns)
      if (length(runs) > 0) {
        first_run <- runs[[1]]
        t_node <- xml2::xml_find_first(first_run, "./w:t", ns)
        if (!is.na(t_node)) {
          split <- oq_split_caption_text(xml2::xml_text(t_node), numbered_count)
          if (isTRUE(split$matched)) {
            anchor_text[[anchor_name]] <- split$rest
            converted_name <- if (isTRUE(caption_options$auto_number)) {
              oq_convert_caption_to_field(p, ns, first_run, split, seq_id, caption_options)
            } else {
              NA_character_
            }
            if (!is.na(converted_name)) {
              converted_anchors <- c(converted_anchors, converted_name)
              n_field_converted <- n_field_converted + 1L
            } else if (needs_text_rewrite) {
              ## If auto_number was set but the field conversion failed
              ## (e.g. no matching bookmark found, see
              ## oq_convert_caption_to_field()), the caption here falls
              ## back to the same static text rewrite as without
              ## auto_number - it should never silently keep Pandoc's
              ## unformatted raw text just because the field conversion
              ## wasn't possible.
              final_pre <- if (!is.null(caption_options$prefix)) caption_options$prefix else split$title_prefix
              final_sep <- if (!is.null(caption_options$separator)) caption_options$separator else split$generated_sep
              oq_write_caption_run(first_run, t_node, ns, final_pre, split$number, final_sep, split$rest, caption_options$number_bold)
              n_text_rewritten <- n_text_rewritten + 1L
            }
          }
        }
      }
    }

    if (!is.null(caption_options$above) && !is.null(content_finder)) {
      content_node <- content_finder(p, ns)
      if (!is.na(content_node)) {
        oq_move_caption(p, content_node, caption_options$above)
        n_moved <- n_moved + 1L
      }
    }
  }

  list(n_found = n_found, n_text_rewritten = n_text_rewritten, n_field_converted = n_field_converted,
       n_moved = n_moved, anchor_text = anchor_text, converted_anchors = converted_anchors)
}
